// Utility functions for the Floww Recruitment Platform

export const generateRoomName = (candidateId) => {
  const adjectives = ['Honest', 'Bright', 'Swift', 'Clear', 'Bold'];
  const nouns = ['Boundaries', 'Concepts', 'Methods', 'Strategies', 'Solutions'];
  const verbs = ['Achieve', 'Create', 'Build', 'Enhance', 'Generate'];
  const adverbs = ['Often', 'Always', 'Quickly', 'Clearly', 'Boldly'];
  const seed = candidateId;
  return `${adjectives[seed % 5]}${nouns[seed % 5]}${verbs[seed % 5]}${adverbs[seed % 5]}`;
};

export const generateAccessToken = () => {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  return Array.from({length: 6}, () => chars[Math.floor(Math.random() * chars.length)]).join('');
};

export const generateCV = (candidate) => {
  const cvContent = `
       CANDIDATE RESUME
===========================================

PERSONAL INFORMATION
Name: ${candidate.name}
Email: ${candidate.email}
Location: ${candidate.location}
Phone: +1 (555) 123-4567

PROFESSIONAL SUMMARY
${candidate.role} with ${candidate.experience} of experience
Score: ${candidate.score}/100

CORE COMPETENCIES
${candidate.skills}

PROFESSIONAL EXPERIENCE
${candidate.role}
Key Achievements:
${candidate.notes}

RECOMMENDATION STATUS
${candidate.recommendation}

===========================================
Generated by Floww Recruitment Platform
`;

  const blob = new Blob([cvContent], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${candidate.name.replace(/\s+/g, '_')}_CV.pdf`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const curiousmindsBrandColors = ['#8B5CF6', '#EC4899', '#F59E0B', '#10B981'];

export const getRandomCuriousMindsColor = () => {
  return curiousmindsBrandColors[Math.floor(Math.random() * curiousmindsBrandColors.length)];
};
